---
- name: Installer la dernière version de kubernetes-client
  hosts: fedora
  become: yes
  tasks:
    - name:  Installer kubernetes-client
      ansible.builtin.yum:
        name: kubernetes-client
        state: latest
